[package]
name = "lapin-async"
version = "0.11.1"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library with a low level API designed for use with mio"
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-async"
keywords = ["amqp", "rabbitmq", "mio"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[dependencies]
log = "^0.4"
nom = "^3.0"
cookie-factory = "^0.2.4"
amq-protocol = "^0.19"

[dependencies.sasl]
version= "^0.4"
default-features = false

[build-dependencies]
amq-protocol = "^0.19"

[dev-dependencies]
env_logger = "^0.5"

[features]
default = []


