[package]
name = "lapin-async"
version = "0.8.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
description = "AMQP client library with a low level API designed for use with mio"
repository = "https://github.com/Geal/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-async"
keywords = ["amqp", "rabbitmq", "mio"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[dependencies]
log = "^0.3"
nom = "^2.2"
cookie-factory = "^0.2"
amq-protocol = "^0.16"
clippy = {version = "^0.0.119", optional = true}

[dependencies.sasl]
version= "^0.4"
default-features = false

[build-dependencies]
amq-protocol = "^0.16"

[dev-dependencies]
env_logger = "^0.4"

[features]
default = []


