[package]
name = "lapin-futures"
version = "0.11.1"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
repository = "https://github.com/Geal/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
nom = "^3.0"
log = "^0.4"
bytes = "^0.4"
futures = "^0.1"
tokio-io = "^0.1"
tokio-timer = "^0.2"
lapin-async = {version = "^0.11", path = "../async"}
cookie-factory = "^0.2"

[dev-dependencies]
nom = "^3.0"
env_logger = "^0.5"
futures = "^0.1"
tokio-core = "^0.1"
