[package]
name = "lapin-futures"
version = "0.4.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
repository = "https://github.com/Geal/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
nom = "^2.2"
log = "^0.3"
bytes = "^0.4"
futures = "^0.1"
tokio-io = "^0.1"
tokio-timer = "^0.1"
lapin-async = "^0.4"
cookie-factory = "^0.2"
amq-protocol = "^0.11"

[dev-dependencies]
nom = "^2.1"
futures = "0.1"
env_logger = "^0.4"
tokio-core = "^0.1"
